#IF YA WANNA USE DIS, PLACE IT IN THE NECESSARY FOLDER AND RUN
#IT'LL OUTPUT THE FILE LIST TO A TXT FILE (PLS WORK)

.PARAMETER IncludeOptional
  Include optional non-INF/CAT/SYS files (DLL/EXE/BIN/DAT). Default: $true

.PARAMETER Extensions
  Custom list of extensions to include. Overrides defaults when supplied.

.PARAMETER Append
  Append to existing files.txt instead of overwriting. Default: $false

  # Run in current folder and generate files.txt:
  .\New-FilesList.ps1

  # Explicit folder, only INF/CAT/SYS:
  .\New-FilesList.ps1 -Root "C:\Repo\drivers\dell\pro14\pc14250\bluetooth" -IncludeOptional:$false

  # Custom extensions:
  .\New-FilesList.ps1 -Extensions ".inf",".cat",".sys",".dll",".mui"
#>

[CmdletBinding()]
param(
  [string]$Root = (Get-Location).Path,
  [bool]$IncludeOptional = $true,
  [string[]]$Extensions,
  [bool]$Append = $false,
  [switch]$DryRun
)

if (-not $Extensions -or $Extensions.Count -eq 0) {
  $Extensions = @(".inf", ".cat", ".sys")
  if ($IncludeOptional) {
    $Extensions += @(".dll", ".exe", ".bin", ".dat")
  }
}

$Extensions = $Extensions | ForEach-Object {
  $e = $_.ToLower().Trim()
  if ($e -notmatch '^\.') { ".$e" } else { $e }
} | Sort-Object -Unique

Write-Verbose "Scanning root: $Root"
Write-Verbose "Extensions: $($Extensions -join ', ')"

function Get-RelativePath {
  param([string]$Base,[string]$Full)
  $uriBase = (Resolve-Path -LiteralPath $Base).Path
  $uriBase = [System.IO.Path]::GetFullPath($uriBase)
  $uriA = New-Object System.Uri($uriBase + [System.IO.Path]::DirectorySeparatorChar)
  $uriB = New-Object System.Uri((Resolve-Path -LiteralPath $Full).Path)
  $rel = $uriA.MakeRelativeUri($uriB).ToString()
  return $rel -replace '/', '/'
}

$all = Get-ChildItem -Path $Root -Recurse -File -ErrorAction Stop |
  Where-Object { $Extensions -contains $_.Extension.ToLower() }

$sorted = $all | Sort-Object @{Expression = { $_.DirectoryName }}, @{Expression = { $_.Name }}

$relPaths = foreach ($f in $sorted) {
  Get-RelativePath -Base $Root -Full $f.FullName
}

$filesTxt = Join-Path -Path $Root -ChildPath "files.txt"

if ($DryRun) {
  Write-Host "Dry run: would write files.txt at: $filesTxt"
  $relPaths | ForEach-Object { Write-Host $_ }
} else {
  if ($Append -and (Test-Path -LiteralPath $filesTxt)) {
    Add-Content -Path $filesTxt -Value ($relPaths -join [Environment]::NewLine)
  } else {
    $header = @(
      "# Auto-generated by New-FilesList.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
      "# Root: $Root",
      "# Included extensions: $($Extensions -join ', ')",
      "# Lines below are relative paths used by the Intune script to download/install drivers.",
      ""
    )
    Set-Content -Path $filesTxt -Value ($header -join [Environment]::NewLine)
    Add-Content -Path $filesTxt -Value ($relPaths -join [Environment]::NewLine)
  }
  Write-Host "files.txt written: $filesTxt"
  Write-Host "Count: $($relPaths.Count) entries"
}

Write-Host "`nTips:"
Write-Host " - Ensure each INF's referenced files (SourceDisksFiles/CopyFiles) exist in the same folder."
Write-Host " - Keep each driver (INF+CAT+SYS+others) together inside a subfolder for clarity."
Write-Host " - The order in files.txt doesn't matter; we sort for readability."
